### ISSUE TITLE
Ignore Blade YAML Front Matter

### ISSUE THREAD

**Issue by lukebouch** [shufo/vscode-blade-formatter#403]
I'm using [Jigsaw](https://jigsaw.tighten.com) as my static site generator and it uses Laravel Blade. I need to add front matter to the top of the blade file with a level of indentation but the formatter always removes the indentation.

## Expected Result
```---
pagination:
  collection: posts
  perPage: 10
---

@extends('_layouts.main')

@section('body')

@endsection
```

## Actual Result
```---
pagination:
collection: posts
perPage: 10
---

@extends('_layouts.main')

@section('body')

@endsection
```

Is there a way to exclude the front matter from being parsed by the formatter?

**Comment by shufo** [comment]
HI @lukebouch.
Currently there is no support for syntax mixed usage in vscode-blade-formatter.

But you can [disable partially by comment](https://github.com/shufo/vscode-blade-formatter#disabling-format-in-file) like this

```yaml
---
# {{-- blade-formatter-disable --}}
title: Blog
description: The list of blog posts for the site
pagination:
    collection: posts
    perPage: 4
# {{-- blade-formatter-enable--}}
---
```

It will preserve indent value in yaml section.

If you would like to ignore enter file, put `.bladeignore` like 

```bash
# Ignore email templates
resources/views/email/**
```
